import { NextResponse } from "next/server";

const seedUsers = [
	{
		id: 1,
		name: "Leanne Graham",
		email: "leanne@example.com",
		username: "Bret",
		company: { name: "Romaguera-Crona" },
		phone: "1-770-736-8031",
		website: "leanne.org",
		address: { city: "Gwenborough" },
	},
	{
		id: 2,
		name: "Ervin Howell",
		email: "ervin@example.com",
		username: "Antonette",
		company: { name: "Deckow-Crist" },
		phone: "010-692-6593",
		website: "ervin.net",
		address: { city: "Wisokyburgh" },
	},
	{
		id: 3,
		name: "Clementine Bauch",
		email: "clementine@example.com",
		username: "Samantha",
		company: { name: "Romaguera-Jacobson" },
		phone: "1-463-123-4447",
		website: "clementine.info",
		address: { city: "McKenziehaven" },
	},
	{
		id: 4,
		name: "Patricia Lebsack",
		email: "patricia@example.com",
		username: "Karianne",
		company: { name: "Robel-Corkery" },
		phone: "493-170-9623",
		website: "patricia.biz",
		address: { city: "South Elvis" },
	},
	{
		id: 5,
		name: "Chelsey Dietrich",
		email: "chelsey@example.com",
		username: "Kamren",
		company: { name: "Keebler LLC" },
		phone: "(254)954-1289",
		website: "chelsey.me",
		address: { city: "Roscoeview" },
	},
	{
		id: 6,
		name: "Mrs. Dennis Schulist",
		email: "dennis@example.com",
		username: "Leopoldo_Corkery",
		company: { name: "Considine-Lockman" },
		phone: "1-477-935-8478",
		website: "dennis.org",
		address: { city: "South Christy" },
	},
	{
		id: 7,
		name: "Kurtis Weissnat",
		email: "kurtis@example.com",
		username: "Elwyn.Skiles",
		company: { name: "Johns Group" },
		phone: "210.067.6132",
		website: "kurtis.io",
		address: { city: "Howemouth" },
	},
	{
		id: 8,
		name: "Nicholas Runolfsdottir",
		email: "nicholas@example.com",
		username: "Maxime_Nienow",
		company: { name: "Abernathy Group" },
		phone: "586.493.6943",
		website: "nicholas.dev",
		address: { city: "Aliyaview" },
	},
	{
		id: 9,
		name: "Glenna Reichert",
		email: "glenna@example.com",
		username: "Delphine",
		company: { name: "Yost and Sons" },
		phone: "(775)976-6794",
		website: "glenna.app",
		address: { city: "Bartholomebury" },
	},
	{
		id: 10,
		name: "Clementina DuBuque",
		email: "clementina@example.com",
		username: "Moriah.Stanton",
		company: { name: "Hoeger LLC" },
		phone: "024-648-3804",
		website: "clementina.co",
		address: { city: "Lebsackbury" },
	},
];

export async function GET() {
	return NextResponse.json(seedUsers);
}
